name: sse
version: 3.6.1-dev
homepage: https://github.com/dart-lang/sse
description: >-
  Provides client and server functionality for setting up bi-directional
  communication through Server Sent Events (SSE) and corresponding POST
  requests.

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  async: ^2.0.8
  collection: ^1.0.0
  logging: ^0.11.3+2
  pedantic: ^1.4.0
  stream_channel: '>=1.6.8 <3.0.0'
  shelf: ^0.7.4

dev_dependencies:
  shelf_static: ^0.2.8
  test: ^1.5.3
  webdriver: ^2.1.0
